FILE = ("Файл", "File")
OPEN = ("Открыть файл", "Open file")
OPEN_FOLDER = ("Открыть папку", "Open folder")
EXIT = ("Выход", "Exit")
VIEW = ("Вид", "View")
SCALE = ("Масштаб", "Scale")
LANG = ("Язык", "Language")

BEGIN = ("Начало", "Begin")
END = ("Конец", "End")
TYPE = ("Тип", "Type")
GO = ("Начать", "Go")
